coffee_shop:
  outputs:
    dev:
      dataset: dbt_models
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: E:\bq_service_accounts\da-portfolio-showcase-1-741e4e391e7c.json
      method: service-account
      priority: interactive
      project: da-portfolio-showcase-1
      threads: 1
      type: bigquery
  target: dev
